### ISSUE TITLE
借用appkey可否

### ISSUE THREAD

**Issue by swordfeng** [NightlyFantasy/Bili_Fix_Player#8]
正在撸HTML5的黑科技（作为尝试……），需要mp4格式的链接
我想以后可能还能加入对其它视频站的直接解析来得到最高画质……

**Comment by swordfeng** [comment]
嗯……让我翻翻评论那个带sign的版本……试试

**Comment by NightlyFantasy** [comment]
appkey是抓来的，所以不用和我借的~\(≧▽≦)/~啦啦啦

**Comment by swordfeng** [comment]
那就关了- -
