### ISSUE TITLE
HTML5 播放器能用？

### ISSUE THREAD

**Issue by laincat** [NightlyFantasy/Bili_Fix_Player#9]
https://github.com/zacyu/bilibili-helper

**Comment by NightlyFantasy** [comment]
我有一个3.9.3.1(蝉鸣you)的版本，用的是原版的B站HTML5播放器，但是因为不支持在火狐和猴子下使用，所以没更新，不过，chrome下的tampermonkey却可以用,地址http://bangumi.ga/bili_fix_player.user.js

**Comment by tiansh** [comment]
我只知道 `location.href =` 应该被改掉，别的我啥都不知道……
https://github.com/greasemonkey/greasemonkey/issues/2232

**Comment by OneWizard** [comment]
话说哔哩哔哩助手的html5播放器能移植吗

**Comment by NightlyFantasy** [comment]
其实我做了助手的H5播放器，但是没发出来，我怕助手不给我这么做哈哈，毕竟不是我的成果

**Comment by tiansh** [comment]
@NightlyFantasy zacyu/bilibili-helper 好像也是 MIT 协议，所以应该表明使用了这个项目的代码，就可以直接用的……

**Comment by myfreeer** [comment]
@tiansh  @NightlyFantasy 
https://github.com/zacyu/bilibili-helper/blob/master/LICENSE
确实是MIT 协议，只要增加版权声明就可以使用源码
